### ISSUE TITLE
Memory Leak when HEAP_OPTS is not set

### ISSUE THREAD

**Issue by BubbaJoe** [prometheus/jmx_exporter#690] opened 2022-03-04 06:48 UTC
Seems that when HEAP_OPTS (MAX MEMORY Option Specifically) is not set, the Prometheus thread crashes sometimes.

**Comment by kiuby88** [comment] 2022-03-18 09:31
Hi @BubbaJoe 

I am running a `jmx-exporter` in K8S. I think I am finding a memory leak because the memory usage trends to up until the container is killed by K8S and it is restarted.
I have checked both dumps of memory, for live and all objects in memory. I have found there are a lot of not live objects waiting to be deleted. 
We will try to set a `HEAP_OPTS` value. 
Just to know, can you elaborate a bit the root cause?
Many thanks

**Comment by fstab** [comment] 2022-04-25 18:23
If you say you are running the `jmx_exporter`, do you mean you attach it as an agent to an existing VM, or are you running it in standalone mode and monitor your application via remote RMI?

If you are using the agent, it would be good to try the standalone mode instead. That way `jmx_exporter` and the JVM being monitored will be two separate processes, and we could see which process has the memory leak.

**Comment by adberger** [comment] 2022-04-26 05:47
In our case we are running the docker image of bitnami jmx-exporter as a sidecar in k8s:

configMap
```
apiVersion: v1
kind: ConfigMap
data:
  jmx-prometheus.yml: |-
    jmxUrl: service:jmx:rmi:///jndi/rmi://127.0.0.1:5555/jmxrmi
    lowercaseOutputLabelNames: true
    lowercaseOutputName: true
    ssl: false
```

pod
```
apiVersion: v1
kind: Pod
spec:
  containers:
  - image: .../jira-software:8.20.8
    name: jira
    ports:
    - containerPort: 5555
      name: jmx
      protocol: TCP
  - command:
    - java
    - -Xmx400m
    - -XshowSettings:vm
    - -jar
    - jmx_prometheus_httpserver.jar
    - "5556"
    - /opt/jmx-config/jmx-prometheus.yml
    image: .../bitnami/jmx-exporter:0
    imagePullPolicy: Always
    name: jmx
    ports:
    - containerPort: 5556
      name: metrics
      protocol: TCP
    resources:
      limits:
        cpu: 150m
        memory: 512Mi
      requests:
        cpu: 150m
        memory: 256Mi
    volumeMounts:
    - mountPath: /opt/jmx-config
      name: jmx-config
```

![memory_usage_jmx](https://user-images.githubusercontent.com/43774417/165230294-75e60b8d-341a-43e5-b767-e03f34408971.png)

**Comment by kiuby88** [comment] 2022-04-26 07:12
@adberger, we had the same situation than you., indeed we found the same memory usage pattern you showed in the picture. 
As I mentioned we tried to set the `HEAP_OPTS`  and this fixed the issue.

**Comment by adberger** [comment] 2022-04-26 07:16
> @adberger, we had the same situation than you., indeed we found the same memory usage pattern you showed in the picture. As I mentioned we tried to set the `HEAP_OPTS` and this fixed the issue.

What do you mean by `HEAP_OPTS`?
Can you provide some more information?

**Comment by fstab** [comment] 2022-04-26 11:35
This could be an issue with an outdated Java version in bitnami's Docker image.

By default, Java uses 1/4 of the available memory as the maximum heap space. For example, on my laptop with 16G memory a JVM has a max heap space of 4G. You can verify this with `java -XX:+PrintFlagsFinal -version | grep MaxHeapSize`:

```
size_t MaxHeapSize                              = 4116709376                                {product} {ergonomic}
```

Now, let's run Java in a Docker container with 1G memory:

```
docker run -ti --cpus 1 -m 1G ubuntu
```

With a current Java verion (I tried the latest OpenJDK 17 release), you will see:

```
size_t MaxHeapSize                              = 268435456                                 {product} {ergonomic}
```

268435456 Bytes is 256M, so it's exactly 1/4 of the memory available to the Docker container. However, if I try the same with the Java version in [bitnami's Dockerfile](https://github.com/bitnami/bitnami-docker-jmx-exporter/blob/master/0/debian-10/Dockerfile), I get the following:

```
uintx MaxHeapSize                              := 4116709376                          {product}
```

So apparently this Java version is an old version that does not have Docker support, i.e. it does not respect the memory limit in the Docker container. Instead, it grabs 1/4 of the underlying host memory, which is 4G in my case.

To deal with this, you can manually set the max heap size with the `-Xmx` command line parameter.

I see that there is a `-Xmx400m` parameter in the Kubernetes deployment you posted above, but I'm not sure how this works in a sidecar. Maybe 400M is too much for your container?

**Comment by adberger** [comment] 2022-04-28 07:57
It seems that setting `-Xmx` alone doesn't work here, because the container sees over 130GB available which will be used for everything outside of the heap:
```
ava -Xmx400m -XX:+PrintFlagsFinal -version | grep -iE 'maxram|MaxHeapSize'
uintx MaxHeapSize                              := 419430400                           {product}
uint64_t MaxRAM                                    = 137438953472                        {pd product}
```

So we set `-XX:MaxRAM` to the same value as the resource.limits of the container:
```
java -XX:MaxRAM=500m -XX:+PrintFlagsFinal -version | grep -iE 'maxram|MaxHeapSize'
uintx MaxHeapSize                              := 132120576                           {product}
uint64_t MaxRAM                                   := 524288000                           {pd product}
```

We are now observing if this solves the issue for now.
(We are on cgroups v2)

**Comment by adberger** [comment] 2022-05-01 15:25
Update: Issue has been solved with `-XX:MaxRAM=500m`:
![Memory](https://user-images.githubusercontent.com/43774417/166152764-43cc2081-2f28-47ba-b892-4d0dcefd91ff.PNG)

**Comment by dhoard** [comment] 2023-06-24 02:23
Closed as resolved.

**Closed by dhoard** 2023-06-24 02:23 UTC
