### ISSUE TITLE
Javaagent HTTP-Server blocks on none System.exit

### ISSUE THREAD

**Issue by Griesbacher** [prometheus/jmx_exporter#196] opened 2017-10-10 06:55 UTC
Hi,

I'm not sure if I missed something but if the program you want to monitor doesn't use System.exit() the HTTP Server blocks and the program does not end. This can be reproduced if the last line of the javaagent IT is left out like following:

```java
package io.prometheus.jmx;

import java.io.IOException;

public class TestApplication {
    public static void main(String[] args) throws IOException {
        System.out.println();
        System.out.flush();
        System.in.read();
        //System.exit(0);
    }
}
```
https://github.com/prometheus/jmx_exporter/blob/master/jmx_prometheus_javaagent/src/test/java/io/prometheus/jmx/TestApplication.java

I think, it is pretty normal not to use System.exit(), if everything went well.

Best regards,
Philip

**Comment by brian-brazil** [comment] 2017-10-10 09:52
Dupe of #170

**Closed by brian-brazil** 2017-10-10 09:52 UTC
