### ISSUE TITLE
When use the java agent there are too many MetricFamilySamples$Sample in the heap

### ISSUE THREAD

**Issue by mingyuanzhu** [prometheus/jmx_exporter#460] opened 2020-01-31 04:26 UTC
I used the javaagent to get some metrics like `java -javaagent:/opt/jmx_exporter/jmx_prometheus_javaagent.jar=8080 ...`, the version is 0.8.0
With the service running day by day we found the CPU usage is increase like this
![image](https://user-images.githubusercontent.com/6222056/73429795-71f0d800-4377-11ea-8f84-fa9255d5f406.png)
And I checked the GC rate trend is same with the CPU increase.
![image](https://user-images.githubusercontent.com/6222056/73429941-c6945300-4377-11ea-9821-83c6ec32d7e8.png)
 And then I used the command `jmap -histo:live 1` to find there were more prometheus jmx relative objects. I am not sure is there memory leak or it is the normal case.
![image](https://user-images.githubusercontent.com/6222056/73430318-b7fa6b80-4378-11ea-9223-86c0cff4f9a2.png)

And after I restarted the service and use `jmap` again, I can not find too many Prometheus objects.

**Comment by brian-brazil** [comment] 2020-01-31 08:31
Dupe of https://github.com/prometheus/client_java/issues/523

**Closed by brian-brazil** 2020-01-31 08:31 UTC
