### ISSUE TITLE
JMX Exporter in ElasticSearch

### ISSUE THREAD

**Issue by Stono** [prometheus/jmx_exporter#865] opened 2023-08-01 08:24 UTC
Hi, 
I'm trying to get the jmx exporter to work in elasticsearch; and deep down a rabbithole!

The error we get is:
```
docker-elasticsearch-app-1  | Exception in thread "main" java.lang.reflect.InvocationTargetException
docker-elasticsearch-app-1  |   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
docker-elasticsearch-app-1  |   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
docker-elasticsearch-app-1  |   at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
docker-elasticsearch-app-1  |   at java.base/java.lang.reflect.Method.invoke(Method.java:568)
docker-elasticsearch-app-1  |   at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:491)
docker-elasticsearch-app-1  |   at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:503)
docker-elasticsearch-app-1  | Caused by: java.lang.NoClassDefFoundError: com/sun/net/httpserver/Authenticator
docker-elasticsearch-app-1  |   at io.prometheus.jmx.JavaAgent.premain(JavaAgent.java:39)
docker-elasticsearch-app-1  |   ... 6 more
docker-elasticsearch-app-1  | Caused by: java.lang.ClassNotFoundException: com.sun.net.httpserver.Authenticator
docker-elasticsearch-app-1  |   at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
docker-elasticsearch-app-1  |   at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
docker-elasticsearch-app-1  |   at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
docker-elasticsearch-app-1  |   ... 7 more
docker-elasticsearch-app-1  | *** java.lang.instrument ASSERTION FAILED ***: "!errorOutstanding" with message Outstanding error when calling method in invokeJavaAgentMainMethod at src/java.instrument/share/native/libinstrument/JPLISAgent.c line: 619
docker-elasticsearch-app-1  | *** java.lang.instrument ASSERTION FAILED ***: "success" with message invokeJavaAgentMainMethod failed at src/java.instrument/share/native/libinstrument/JPLISAgent.c line: 459
docker-elasticsearch-app-1  | *** java.lang.instrument ASSERTION FAILED ***: "result" with message agent load/premain call failed at src/java.instrument/share/native/libinstrument/JPLISAgent.c line: 422
docker-elasticsearch-app-1  | FATAL ERROR in native method: processing of -javaagent failed, processJavaStart failed
```

i'm trying with a noddy config:
```
startDelaySeconds: 0
lowercaseOutputLabelNames: false
ssl: false
lowercaseOutputName: false
whitelistObjectNames:
  - "java.lang:type=OperatingSystem"
```

this is on Java 17, exporter version 0.19.0.

Any ideas what i'm doing wrong?  I've got this exporter working in every other java app!  So really struggling :)

**Comment by Stono** [comment] 2023-08-01 08:53
Probably linked: https://github.com/prometheus/client_java/issues/533

**Comment by dhoard** [comment] 2023-08-03 21:11
Closing as duplicate of https://github.com/prometheus/jmx_exporter/issues/850

**Closed by dhoard** 2023-08-03 21:11 UTC
Labels: status: duplicate, theme: configuration
