### ISSUE TITLE
JMX metrics containing quotes are lost

### ISSUE THREAD

**Issue by tooptoop4** [prometheus/jmx_exporter#689] opened 2022-03-01 13:51 UTC
I have this config:
```
jmxUrl: service:jmx:rmi:///jndi/rmi://localhost:{{ .Values.jmx.port }}/jmxrmi
lowercaseOutputName: true
lowercaseOutputLabelNames: true
ssl: false
rules:
- pattern: "debezium.([^:]+)<type=connector-metrics, context=([^,]+), server=([^>]+)>([^:]+)"
  name: debezium_metrics_$4
  labels:
    plugin: "$1"
    name: "$3"
    context: "$2"
```

jmx values like these are being exposed to prometheus (as expected):
,"debezium.oracle:type=connector-metrics,context=streaming,server=my-topicoracle,attr=QueueRemainingCapacity":81920
,"debezium.oracle:type=connector-metrics,context=streaming,server=my-topicoracle,attr=MiningSessionUserGlobalAreaMemoryInBytes":7595872

**BUT issue is metrics like these were the values contain quotes are not being sent:**
,"debezium.oracle:type=connector-metrics,context=streaming,server=my-topicoracle,attr=CurrentScn":"521761522525"
,"debezium.oracle:type=connector-metrics,context=streaming,server=my-topicoracle,attr=LastEvent":"position: {scn: 6533}, key: {\"ID\" : \"421\", \"CONTRACT_NUMBER\" : \"redac\", \"ATTRIB4\" : null}"

**Comment by tooptoop4** [comment] 2022-11-19 00:53
seems string type not supported:
https://github.com/prometheus/jmx_exporter/issues/255
https://github.com/prometheus/jmx_exporter/issues/586
https://github.com/prometheus/jmx_exporter/issues/548
https://github.com/prometheus/jmx_exporter/issues/266
https://github.com/prometheus/jmx_exporter/issues/377

**Comment by dhoard** [comment] 2024-04-25 05:26
Closing due to working as designed.

**Closed by dhoard** 2024-04-25 05:26 UTC
Labels: status: working as designed
